### ISSUE TITLE
Not able to save collage

### ISSUE THREAD

**Issue by bhattaxay** [tzsk/collage#7]
Hii there,

I am using you extension and it's working fine upto.
``` $image = $collage->make(400, 400)->from($images);```
Can you pls describe more about how to save that image using intervention i am not able to save that image as you mentioned in  your documents:

Return Value
The reaturned $image is the instance of Intervention\Image\Image object.

You can do multiple things with it.

You can save the final collage.
You can just use it as a plain response.
You can crop/resize/colorize and more.
Read more about what you can do in the Official Documentation.

Can you describe more about How to use this object Intervention\Image\Image in image intervention?

**Comment by tzsk** [comment]
@bhattaxay 

Actually it says right there
>Read more about what you can do in the [Official Documentation](http://image.intervention.io/).

Intervention is a popular php image manipulation library. Which is out of the scope of this Package. If you want to know how to work with Intervention Image go to the official docs by clicking on the link.

http://image.intervention.io/

**Comment by bhattaxay** [comment]
Ok i have done with intervention. Can you pls explain in brief about custom generator. I am not getting more idea about you have mentioned in your documentation regarding custom generator.
