### ISSUE TITLE
This lib uses the Laraval helper functions "with" and "collect"

### ISSUE THREAD

**Issue by chrfritsch** [tzsk/collage#70]
Currently, this library can't be used outside of Laravel because it uses internal Laravel functions.

**Comment by tzsk** [comment]
@chrfritsch it can be, if you install it via composer. We have Unit-Tests to verify that.

**Comment by chrfritsch** [comment]
I opened https://github.com/tzsk/collage/pull/71. I hope we get it merged because I would like to use this library in a drupal project.

**Comment by tzsk** [comment]
@chrfritsch can you not install it via composer? Or is that not an option?

**Comment by chrfritsch** [comment]
I installed with composer. Laravel is only a dev dependency. So I don't get it. And I think it would be nice when I don't need the whole laravel framework to run this.

**Comment by chrfritsch** [comment]
So this would really help me, that I don’t have to mess around with gd or Imagick

**Comment by chrfritsch** [comment]
Would you also accept a PR for collage v4? Drupal still supports PHP7.3 so I can't use v5...

**Comment by chrfritsch** [comment]
Ah, in v4 is a dependency on illuminate/support. So we don't need a patch. But nevertheless, I think it would be nice to get the PR for v5 merged.

**Comment by tzsk** [comment]
I removed framework dependency and added support. I kinda like Laravel helpers.
